name: trench2richies
description: Trenches to Riches app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  url_launcher: ^6.2.5
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/banner.png
    - assets/Bitcoin.png
    - assets/Bitcoin_QR.png
    - assets/cashapp.png
    - assets/Litcoin.png
    - assets/Litecoin_QR.png
    - assets/Usdt.png
    - assets/Usdt_QR.png
    - assets/images/img1.jpeg
    - assets/images/img2.jpeg
    - assets/images/img3.jpeg
    - assets/images/img4.jpeg
    - assets/images/img5.jpeg
    - assets/images/img6.jpeg
    - assets/images/img7.jpeg
    - assets/images/img8.jpeg
    - assets/images/img9.jpeg
    - assets/images/img10.jpeg
    - assets/images/img11.jpeg
    - assets/images/img12.jpeg
